// Type declarations for image file imports.
// next-env.d.ts provides these via next/image-types/global when Next.js runs,
// but that file is gitignored as it is auto-generated by Next.js at runtime.
// These declarations ensure TypeScript can resolve SVG and PNG imports at
// type-check time (e.g. in CI without a Next.js build).

/** Matches the shape of Next.js StaticImageData without importing from internal paths. */
interface StaticImageData {
    src: string;
    height: number;
    width: number;
    blurDataURL?: string;
    blurWidth?: number;
    blurHeight?: number;
}

declare module '*.svg' {
    // Use `any` to avoid conflicts with @svgr/webpack or babel-plugin-inline-react-svg.
    const content: any;
    export default content;
}

declare module '*.png' {
    const content: StaticImageData;
    export default content;
}
